// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RepeatRestaurant.Models;
using System;

namespace RepeatRestaurant.Migrations
{
    [DbContext(typeof(RepeatRestaurantContext))]
    [Migration("20180219163141_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("RepeatRestaurant.Models.thisUserReview", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("restaurant_name")
                        .IsRequired();

                    b.Property<string>("review")
                        .IsRequired();

                    b.Property<string>("reviewer_name")
                        .IsRequired();

                    b.Property<int>("stars");

                    b.Property<DateTime>("visit_date");

                    b.HasKey("id");

                    b.ToTable("review_table");
                });
#pragma warning restore 612, 618
        }
    }
}
